language: node_js
node_js: stable

sudo: false

install: true

addons:
  firefox: latest
  chrome: stable

os:
  - linux

before_script:
  - npm install

branches:
  only: master

notifications:
  email: true

cache:
  directories: node_modules

script:
  - npm run package
